"""Your migration message

Revision ID: 2e514b929bf9
Revises: bb25e356ee9e
Create Date: 2023-11-11 13:03:36.201294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e514b929bf9'
down_revision = 'bb25e356ee9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('runs_by_week_matrix', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('runs_by_week_matrix')

    # ### end Alembic commands ###
