"""added the run_matrix and totalDistance_matrix to the user class

Revision ID: bb25e356ee9e
Revises: caf0ba25c359
Create Date: 2023-11-11 12:20:57.481011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb25e356ee9e'
down_revision = 'caf0ba25c359'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('run_matrix', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('totalDistance_matrix', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('totalDistance_matrix')
        batch_op.drop_column('run_matrix')

    # ### end Alembic commands ###
